### ISSUE TITLE
Vault client silently generates too-powerful tokens if vault host URL ends in a slash

### ISSUE THREAD

**Issue by emk** [ChrisMacNaughton/vault-rs#14]
We're making heavy use of `vault-rs` for production deploys, and it's working great!

But we discovered a tricky issue. There's a lot of code in `vault-rs` that concatenates URL fragments using `{}{}`. For example:

``` rust
    fn get(&self, endpoint: &str, wrap_ttl: Option<&str>) -> Result<Response> {
        let mut req = self.client
            .get(&format!("{}{}", self.host, endpoint)[..])
```

These low-level HTTP routines are called by higher level routines that include leading slashes:

``` rust
let mut res = try!(self.post("/v1/auth/token/create", Some(&body)));
```

If the passed-in `host` value is of the form `https://vault.example.com/`, then this will generate a URL of the form `https://vault.example.com//v1/auth/token/create` with a double slash `//`.
## The plot thickens

When I use this URL to create a new token, the following series of events happen deep inside hyper:
1. Hyper issues a `POST //v1/auth/token/create` (two slashes) containing JSON data in the body. This JSON data contains a `policies` field saying what vault policies the apply to the newly created token.
2. Vault redirects this to `/v1/auth/token/create`.
3. Hyper retries with `POST /v1/auth/token/create` (one slash) but **without any JSON data in the body**. No `policies` field is present.
4. Vault issues a token that **inherits all the policies of its parent token**.

The fix here is to build URLs using the `url` crate and not `format!`, or at least to strip any trailing slash from the supplied `host`.

I'm going to be very busy this coming week, but if you want, I can try to find time to prepare a PR converting the code to use `url` internally.

**Comment by compressed** [comment]
Ah, this isn't good. I was meaning to do that change in the beginning, but then didn't end up doing it. I'll take a crack at this today. I have other breaking changes in #13 so this change can go with that one.

**Comment by emk** [comment]
Thank you so much!

While you're at it, what are the pros and cons of having a Client type without a lifetime parameter? The lifetime parameter makes it slightly harder to store a client in another object, which means I reinitialize the client to often, allowing things down with extra HTTP requests. I can work around this, but since you're revisiting this part of the API, I thought I'd ask. :-)

**Comment by compressed** [comment]
Good question 😄 

Yes, the lifetime parameter should go away with this change. I've found it a bit cumbersome as well, especially across threads since it then requires `host` to have a `'static` lifetime (scoped threads, e.g. crossbream solves this), but it is still is more trouble that it's worth.

I believe the only pro to keeping a reference to the `host` is that you avoid one allocation, but I don't see that as a deal-breaker...

**Comment by compressed** [comment]
Check out #15 for this fix. No test case though. Will add in #13.

Also, @emk, since you are using vault-rs in production, I'd like your opinion on #13, specifically my question there: how to handle vault releases and incompatibility.
