### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by davidiw** [ChrisMacNaughton/vault-rs#29]
I wanted to use this client to access KV-v2, but the API for "call_endpoint" isn't in the latest released version (on crates.io). Could you release a newer version that contains this API?

Thanks!

**Comment by ChrisMacNaughton** [comment]
Sure, released [0.7.0](https://crates.io/crates/hashicorp_vault/0.7.0) just now!

**Comment by ChrisMacNaughton** [comment]
As I released that one, I discovered that openssl-sys (via reqwest) doesn't work with the version of OpenSSL on Ubuntu Bionic nor Focal, so there will likely be another release soon-ish to resolve that (yay updating versions of dependencies :-/)
