### ISSUE TITLE
set_secret not accepting JSON or JSON string

### ISSUE THREAD

**Issue by mtodescato** [ChrisMacNaughton/vault-rs#38]
Hi,
Maybe i missed it, but it seems that is only possible to store a string as a secret even thought Vault can accept JSON file or values. 
The only way i've found to store a json is to encode it as a base64 string?
If not present are you considering to implement this feature?

Thanks

**Comment by ChrisMacNaughton** [comment]
I believe that this is now implemented via: https://github.com/ChrisMacNaughton/vault-rs/pull/39
