### ISSUE TITLE
More APIs? (auth_token.create, auth_token.renew, sys.policies)

### ISSUE THREAD

**Issue by emk** [ChrisMacNaughton/vault-rs#5]
Hello, thank you for providing a great Vault library for Rust!

I'm the maintainer of https://github.com/faradayio/add-vault-tokens, a simple Ruby library for adding vault tokens to a `docker-compose` file. This uses the vault API to do three things:
1. Enumerate all policies available from vault.
2. Create new tokens.
3. Renew existing tokens.

I'm porting the Ruby code to Rust, and I need to re-implement these three Vault APIs in Rust. Would you be interested in me implementing these APIs as a pull request and submitting them to your library?

(I may also want to want to switch https://github.com/emk/credentials to use your Vault client instead of my hand-rolled one at some point, but that's a topic for another day.)

**Comment by ChrisMacNaughton** [comment]
I would love contributions! Ideally, I'd like this to become a fully community run set of API bindings for Vault but so far, it's been me (and one other guy) basically building the things we need. Looking forward to the pull request!

**Comment by emk** [comment]
OK, the first pull request is queued up as #6, and if you like it, I'm happy to send you a couple more. 🙂

**Comment by ChrisMacNaughton** [comment]
I'm looking through it now :)

**Comment by ChrisMacNaughton** [comment]
I've modified the build matrix to hopefully complete faster, as well as adding in Vault 0.6.1 with #8

**Comment by ChrisMacNaughton** [comment]
just merged in #10

**Comment by ChrisMacNaughton** [comment]
And just cut [v0.6.1](https://crates.io/crates/hashicorp_vault/0.6.1)

**Comment by emk** [comment]
Great! I think we've implemented everything here. Thank you so much for reviewing and merging everything.
