### ISSUE TITLE
Replace `println!` with `log` crate, and be very careful about not leaking secrets to logs (at least at `debug` and above?)

### ISSUE THREAD

**Issue by emk** [ChrisMacNaughton/vault-rs#9]
OK, one more suggestion for your consideration. :-)

Right now, the crate contains debugging messages such as:

``` rust
        println!("Vault request failed: {:?}, error message: `{}`",
                 res,
                 error_msg);
```

...and:

``` rust
    println!("Response: {:?}", &body);
```

This has two drawbacks:
1. It causes programs using this library to very noisy.
2. Secrets may be leaked to standard output, and wind up in logs somewhere, which is often against policy for people using vault.

To fix (1), we could simple use the `log` crate. To fix (2), we'd either need to give up certain useful logging output, or perhaps relegate it to the `trace!` level, so it won't show up when normally when debug logging is activated. Even then, it's worth thinking about the security issues carefully.

**Comment by emk** [comment]
(As always, I'm happy to submit PRs.)

**Comment by ChrisMacNaughton** [comment]
I'll see about getting a PR up to handle this in a bit :)

**Comment by ChrisMacNaughton** [comment]
well, the 2nd one is an easy trace! as all it will end up doing is adding more readable syntax to the byte stream that hyper will return. The first example though can be entirely removed as we return an Err with the same message!

**Comment by emk** [comment]
Thank you! Looks great.
